# Generated by Django 5.0.2 on 2024-04-26 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cursos', '__first__'),
        ('Persona', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Persona.persona')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Cursos.curso')),
            ],
        ),
    ]
