# Generated by Django 5.0.2 on 2024-05-02 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudiantes', '0001_initial'),
        ('Persona', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='ci_estudiante',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='id',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ci',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='Persona.persona'),
        ),
    ]
