# Generated by Django 5.0.2 on 2024-05-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Persona', '__first__'),
        ('Rol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ci', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, serialize=False, to='Persona.persona')),
                ('password', models.CharField(max_length=50)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Rol.rol')),
            ],
        ),
    ]
